#!/bin/bash

# --- Install PostgreSQL if not already installed --- #

# Check for postgres existence.
if [[ "$( which postgres )" ]]; then
	echo "Postgres detected -- Skipping installation"
else
	echo "Postgres not detected -- Installing..."

	# Make sure supported Linux flavor is running.
	if [[ "$( which apt-get )" ]]; then
		apt-get install postgresql postgresql-contrib
	else
		echo "Skipping postgres installation...Linux flavor not an APT system. Will need to be done manually."
	fi

	echo "Starting Postgres..."
	pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
fi