#!/bin/bash

# --- Install kops if not already installed --- #

# Check for kops existence.
if [[ "$( which kops )" ]]; then
	echo "kops detected -- Skipping installation"
else
	echo "kops not detected -- Installing..."
	wget -O kops https://github.com/kubernetes/kops/releases/download/$(curl -s https://api.github.com/repos/kubernetes/kops/releases/latest | grep tag_name | cut -d '"' -f 4)/kops-linux-amd64
	chmod u+x ./kops
	mv ./kops /usr/local/bin/
fi