#!/bin/bash

# --- Install kubectl if not already installed --- #

if [[ "$( which kubectl )" ]]; then
	echo "kubectl detected -- Skipping installation"
else
	echo "kubectl not detected -- Installing..."
	wget -O kubectl https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
	chmod u+x ./kubectl
	sudo mv ./kubectl /usr/local/bin/kubectl
fi