language: go

go: 1.10.x

before_install:
  - sudo apt-get update
  - sudo apt-get install -y unzip --no-install-recommends
  - sudo apt-get autoremove -y
  - sudo apt-get clean -y
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

install:
  - dep ensure -vendor-only
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

script:
  - make test