#!/bin/bash

# --- Create new AWS IAM key pair for provided AWS user name --- #

user_name="$1"

if aws iam list-access-keys --user-name "$user_name" | jq ".AccessKeyMetadata"; then
	echo "Access keypair for IAM user \"$user_name\" already exists."
else
	echo "Creating new access keypair for IAM user \"$user_name\"."
	aws iam create-access-key --user-name "$user_name"

	echo "Configuring aws to use \"$user_name\" user..."
	echo "Enter the keys for the key pair just created..."
	aws configure
fi

access_key=$(aws configure get aws_access_key_id)
secret_access_key=$(aws configure get aws_secret_access_key)

echo "Exporting AWS_ACCESS_KEY_ID=\"$access_key\""
echo "Exporting AWS_SECRET_ACCESS_KEY=\"$secret_access_key\""
echo "Set these as environment variables in each of your *.env files."

export AWS_ACCESS_KEY_ID="$access_key"
export AWS_SECRET_ACCESS_KEY="$secret_access_key"