#!/bin/bash

# --- Create new AWS IAM key pair for provided AWS user name --- #

user_name="$1"

if aws iam list-access-keys --user-name "$user_name" | jq ".AccessKeyMetadata"; then
	echo "Access keypair for IAM user \"$user_name\" already exists. Exporting credentials."
else
	echo "Creating new access keypair for IAM user \"$user_name\"."
	aws iam create-access-key --user-name "$user_name"

	echo "Configuring aws to use \"$user_name\" user..."
	echo "Enter the keys for the key pair just created..."
	aws configure
fi

export AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)