#!/bin/bash

# --- Create AWS S3 bucket with provided name --- #

bucket_name="$1"

echo "Creating S3 bucket \"$bucket_name\"..."

if aws s3api create-bucket --bucket "$bucket_name"; then
	echo "Successfully created S3 bucket."
else
	echo "Failed to create S3 bucket. Exiting."
	exit
fi