#!/bin/bash

# --- Create AWS user and attach it to a specific AWS group --- #

user_name="$1"
group_name="$2"

if aws iam list-users | jq "[.Users[] | .UserName]" | grep "\"$user_name\""; then
	echo "IAM user \"$user_name\" already exists. Skipping creation."
else
	echo "Creating IAM user \"$user_name\" and attaching to group \"$group_name\"..."
	aws iam create-user --user-name "$user_name"
	aws iam add-user-to-group --user-name "$user_name" --group-name "$group_name"
fi