#!/bin/bash

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cluster_name="$1"
domain="$2"
state="$3"
zones="$4"
master_size="$5"
node_size="$6"
node_count="$7"
image="$8"
k8s_version="$9"
user_name="kops"
group_name="kops"

# Create aws group.
$this_dir/create_group "$group_name"

# Create aws user and attach to group.
$this_dir/create_user "$user_name" "$group_name"

# Configure new key pair for user.
$this_dir/configure_user "$user_name"

# If state doesn't exist yet for cluster, create S3 bucket to serve that purpose.
if [[ ! "$state" ]]; then
	# Create name for S3 bucket, combining cluster name with a uuid.
	uuid=$( uuidgen )
	uuid="${uuid:0:8}"
	bucket_name="$cluster_name-$uuid"

	# Create the bucket.
	$this_dir/create_bucket "$bucket_name"

	# Give state a value using new bucket name.
	state="s3://$bucket_name"
fi

# Create hosted zone.
$this_dir/create_hosted_zone "$cluster_name" "$domain"

# Create kubernetes cluster.
kops create cluster \
	--name "$cluster_name.$domain" \
	--zones "$zones" \
	--master-size "$master_size" \
	--node-size "$node_size" \
	--node-count "$node_count" \
	--state "$state" \
	--image "$image" \
	--kubernetes-version "$k8s_version" \
	--yes