#!/bin/bash

# --- Create AWS user and attach it to a specific AWS group --- #

user_name="$1"
group_name="$2"

echo "Creating aws user \"$user_name\" and attaching to group \"$group_name\"..."
aws iam create-user --user-name "$user_name"
aws iam add-user-to-group --user-name "$user_name" --group-name "$group_name"