#!/bin/bash

# --- Upsert access keypair for an IAM user --- #

user_name="$1"

keypair_exists=$( aws iam list-access-keys --user-name "$user_name" | jq ".AccessKeyMetadata" )

if [[ "$keypair_exists" ]]; then
	echo "IAM user \"$user_name\" already has an access key. Skipping creation."
else
	echo "Creating new access keypair for IAM user \"$user_name\"..."
	aws iam create-access-key --user-name "$user_name"

	echo "Configuring aws to use \"$user_name\" user..."
	echo "Enter the keys for the key pair just created..."
	aws configure
fi

access_key=$(aws configure get aws_access_key_id)
secret_access_key=$(aws configure get aws_secret_access_key)

echo "Exporting AWS_ACCESS_KEY_ID=\"$access_key\""
echo "Exporting AWS_SECRET_ACCESS_KEY=\"$secret_access_key\""
echo "Set these as environment variables in each of your *.env files."

export AWS_ACCESS_KEY_ID="$access_key"
export AWS_SECRET_ACCESS_KEY="$secret_access_key"