#!/bin/bash

# --- Upsert AWS group (and policy) with provided name --- #

group_name="$1"

group_exists=$( aws iam list-groups | jq "[.Groups[] | .GroupName]" | grep "\"$group_name\"" )

if [[ "$group_exists" ]]; then
	echo "IAM group \"$group_name\" already exists. Skipping creation."
else
	echo "Creating IAM group \"$group_name\"..."
	aws iam create-group --group-name "$group_name"
	aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonEC2FullAccess --group-name "$group_name"
	aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonRoute53FullAccess --group-name "$group_name"
	aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonS3FullAccess --group-name "$group_name"
	aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/IAMFullAccess --group-name "$group_name"
	aws iam attach-group-policy --policy-arn arn:aws:iam::aws:policy/AmazonVPCFullAccess --group-name "$group_name"
fi