#!/bin/bash

# --- Verify an AWS Route53 Change Has a Particular ChangeInfo Status --- #

change_id="$1"
expected_status="$2"
verify_msg="Waiting for change status to be \"$expected_status\"..."
current_status=""

until [[ "$current_status" == "$expected_status" ]]; do
	echo "$verify_msg"
	current_status=$( aws route53 get-change --id "$change_id" | jq -r ".ChangeInfo.Status" )
	sleep 3
done