#!/bin/bash

# --- Install homebrew if not already installed --- #

if [[ "$( which brew )" ]]; then
	echo "homebrew detected -- Skipping installation"
else
	echo "homebrew not detected -- Installing..."
	/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi