#!/bin/bash

# --- Install PostgreSQL if not already installed --- #

if [[ "$( which postgres )" ]]; then
	echo "Postgres detected -- Skipping installation"
else
	echo "Postgres not detected -- Installing..."
	brew install postgresql

	echo "Starting Postgres..."
	pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
fi