#!/bin/bash

# --- Perform an API call to the Core cluster for a specific environment --- #

# ======== PARSE ARGS ======== #

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
env="$1"
method="$2"
route="$3"
payload="$4"

# ======== VALIDATE ARGS ======== #

$this_dir/validate_arg "env" "$env" "local|dev|staging|prod"
$this_dir/validate_arg "method" "$method" "GET|POST|PUT|DELETE"

# ======== GET ENV VALS ======== #

domain=$( $this_dir/env_reader "$env" "DOMAIN" )
rest_api_token=$( $this_dir/env_reader "$env" "REST_API_TOKEN" )
api_version=$( $this_dir/env_reader "$env" "API_VERSION" )

$this_dir/assert_env "DOMAIN" "$domain"
$this_dir/assert_env "REST_API_TOKEN" "$rest_api_token"
$this_dir/assert_env "API_VERSION" "#$api_version"

# ======== FORMAT CURL ARGS ======== #

# Create base url for API call based on if DOMAIN is localhost or not.
if [[ "$env" == "local" ]]; then
	# Attempt to get port from envs, but default to 80.
	port=$( $this_dir/env_reader "$env" "SERVER_PORT" )
	port="${port:-80}"

	hostname="$domain"

	# Add port if not 80
	if [[ "$port" != "80" ]]; then
		hostname+=":$port"
	fi

	base_url="http://$hostname"
else
	base_url="https://api.$domain"
fi

url="$base_url/$api_version${route}"

# Get content type based on method.
if [ "$method" == "GET" ] || [ "$method" == "DELETE" ]; then
	content_type="application/x-www-form-urlencoded"
else
	content_type="application/json"
fi

# Add payload if there is one.
if [[ "$payload" ]]; then
	payload="-d $payload"
fi

# ======== PERFORM API CALL ======== #

curl "$payload" \
	-H "Content-Type: $content_type" \
	-H "Sweet-Tea-Api-Token: $rest_api_token" \
	-X "$method" \
	"$url"