#!/bin/bash

# --- Create Sweet Tea User in database of specified environment --- #

# ======== PARSE ARGS ======== #

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
env="$1"
email="$2"
password="$3"
admin="$4"

# ======== VALIDATE ARGS ======== #

$this_dir/validate_arg "env" "$env" "local|dev|staging|prod"
$this_dir/validate_arg "admin" "$admin" "true|false"
$this_dir/validate_arg "email" "$email"
$this_dir/validate_arg "password" "$password"

# ======== PROMPT EXECUTOR USER FOR CREDENTIALS ======== #

executor_email=""
executor_password=""

printf "Enter your credentials for the $env Sweet Tea environment.\n"

until [[ "$executor_email" ]]; do
	read -p 'Email: ' executor_email
done

until [[ "$executor_password" ]]; do
	read -sp 'Password: ' executor_password
done

# ======== PERFORM API CALL ======== #

payload="{
	\"executor_email\": \"$executor_email\",
	\"executor_password\": \"$executor_password\",
	\"new_email\": \"$email\",
	\"new_password\": \"$password\",
	\"admin\": $admin
}"

printf "\nCreating user...\n"

$this_dir/core_api_call "$env" "POST" "/users" "$payload"