#!/bin/bash

# --- Create Sweet Tea Company in database of specified environment --- #

# ======== PARSE ARGS ======== #

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
env="$1"
name="$2"

# ======== VALIDATE ARGS ======== #

$this_dir/validate_arg "env" "$env" "local|dev|staging|prod"
$this_dir/validate_arg "name" "$name"

# ======== PROMPT CALLING USER FOR CREDENTIALS ======== #

calling_email=""
calling_password=""

printf "Enter your credentials for the $env Sweet Tea environment.\n"

until [[ "$calling_email" ]]; do
	read -p 'Email: ' calling_email
done

until [[ "$calling_password" ]]; do
	read -sp 'Password: ' calling_password
done

# ======== PERFORM API CALL ======== #

payload="{
	\"calling_email\": \"$calling_email\",
	\"calling_password\": \"$calling_password\",
	\"name\": \"$name\"
}"

printf "\nCreating company...\n"

$this_dir/core_api_call "$env" "POST" "/companies" "$payload"