#!/bin/bash

# --- Create Sweet Tea Company in database of specified environment --- #

# ======== PARSE ARGS ======== #

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
env="$1"
name="$2"

# ======== VALIDATE ARGS ======== #

$this_dir/validate_arg "env" "$env" "local|dev|staging|prod"
$this_dir/validate_arg "name" "$name"

# ======== PROMPT EXECUTOR USER FOR CREDENTIALS ======== #

executor_email=""
executor_password=""

printf "Enter your credentials for the $env Sweet Tea environment.\n"

until [[ "$executor_email" ]]; do
	read -p 'Email: ' executor_email
done

until [[ "$executor_password" ]]; do
	read -sp 'Password: ' executor_password
done

# ======== PERFORM API CALL ======== #

payload="{
	\"executor_email\": \"$executor_email\",
	\"executor_password\": \"$executor_password\",
	\"name\": \"$name\"
}"

printf "\nCreating company...\n"

$this_dir/core_api_call "$env" "POST" "/companies" "$payload"