#!/bin/bash

# --- Get the docker image tag for a specific app name --- #

case "$1" in
    server*)  TAG="rest-api";;
    migrate*) TAG="rest-api-migration";;
    worker*)  TAG="rest-api-worker";;
    *)		  TAG=""
esac

echo "$TAG"