#!/bin/bash

# --- Install everything required to get up and running with Sweet Tea --- #

set -e # exit if any child script exits with non-zero status

# Directory of this script.
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Current os -- will exit if not mac or linux.
os="$( $this_dir/curr_os )"

if [[ "$os" = "mac" ]]; then
	# Install homebrew if on mac.
	$this_dir/mac/install_homebrew

elif [[ "$os" = "unknown" ]]; then
	# Exit early if not on mac or linux.
	echo "Only Linux and Mac operating systems supported. Exiting..."
	exit 1
fi

# Install jq to help with bash json parsing.
$this_dir/$os/install_jq

# Install minikube for local k8s development.
$this_dir/$os/install_minikube

# Install kops.
$this_dir/$os/install_kops

# Install kubectl.
$this_dir/$os/install_kubectl

# Upsert files/dirs that were gitignored and should now exist.
$this_dir/upsert_gitignorables

# Install 'dep' -- Go package management tool used with this project.
$this_dir/$os/install_dep

# Install third-party Go packages listed in Gopkg.toml.
$this_dir/install_pkgs

# Install Redis.
$this_dir/install_redis

# Install PostgreSQL.
$this_dir/$os/install_pg

# Upsert local databases for dev and testing.
# Commenting out for now and using cloud-based DBs even for local development.
# ^This avoids the headache of exposing local dbs to a local minikube cluster.
# $this_dir/setup_dbs

echo "Done!"