#!/bin/bash

# --- Install Redis if not already installed --- #

if [[ "$( which redis-server )" ]]; then
	echo "Redis detected -- Skipping installation"
else
	echo "Redis not detected -- Installing..."

	# Switch to /tmp dir for download/installation
	og_dir="$( pwd )"
	cd /tmp

	# Download and unpack Redis v5.0
	wget https://github.com/antirez/redis/archive/5.0-rc1.tar.gz
	tar xzf 5.0-rc1.tar.gz

	# Build and install redis binaries to /usr/local/bin
	cd redis-5.0-rc1
	make
	make install

	# Switch back to original dir
	cd "$og_dir"
fi