#!/bin/bash

# --- Delete and re-create the core, train, and build local clusters --- #

set -e # exit if any child script exits with non-zero status

# ======== PARSE ARGS ======== #

this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
role="$1"
uppercase_role=$( echo "$role" | tr "[:lower:]" "[:upper:]" )

# ======== VALIDATIONS ======== #

$this_dir/validate_arg "role" "$role" "core|build|train"

# Ensure minikube is installed.
if [[ ! "$( which minikube )" ]]; then
	echo "Minikube not detected...run 'make install' and then try again."
	exit 1
fi

# ======== REBUILD CLUSTER ======== #

# Get name of cluster for this role from envs and ensure it exists.s
cluster_name=$( $this_dir/env_reader "local" "${uppercase_role}_CLUSTER_NAME" )
$this_dir/assert_env "${uppercase_role}_CLUSTER_NAME" "$cluster_name"

# Delete cluster from minikube.
minikube delete --profile "$cluster_name"

# Delete cluster and context from kubeconfig.
kubectl config delete-cluster "$cluster_name"
kubectl config delete-context "$cluster_name"

# Upsert cluster on minikube.
$this_dir/upsert_local_cluster "$role" "$cluster_name"