#!/bin/bash

# --- Setup databases and database roles for dev and test environments --- #

set -e # exit if any child script exits with non-zero status

# Directory of this script
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Database name and role name for the dev environment tier
dev_name="rest-api"

# Database name and role name for the testing environment tier
test_name="rest-api-test"

# Upsert roles.
$this_dir/upsert_db_role "$dev_name"
$this_dir/upsert_db_role "$test_name"

# Upsert databases.
$this_dir/upsert_db "$dev_name" "$dev_name"
$this_dir/upsert_db "$test_name" "$test_name"