#!/bin/bash

# --- Upsert Postgres role by name --- #

role_name="$1"

# If role already exists...
if psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$role_name'" | grep -q 1; then
	echo "User \"$role_name\" already exists. Not creating."
else
	# User role doesn't exist yet -- create it with specified name.
	echo "Creating user role \"$role_name\"."
	createuser -s "$role_name"
fi