#!/bin/bash

# --- Upsert Postgres role by name --- #

role_name="$1"

if psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$role_name'" | grep -q 1; then
	echo "User \"$role_name\" already exists. Not creating."
else
	echo "Creating user \"$role_name\"."
	createuser -s "$role_name"
fi