#!/bin/bash

# --- Upsert Postgres role by name --- #

ROLE_NAME="$1"

if psql postgres -tAc "SELECT 1 FROM pg_roles WHERE rolname='$ROLE_NAME'" | grep -q 1; then
	echo "User \"$ROLE_NAME\" already exists. Not creating."
else
	echo "Creating user \"$ROLE_NAME\"."
	createuser -s "$ROLE_NAME"
fi