#!/bin/bash

# --- Upsert database by name and owner role (assumes owner role exists) --- #

owner="$1"
db_name="$2"

if psql postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$db_name'" | grep -q 1; then
	echo "Database \"$db_name\" already exists. Not creating."
else
	echo "Creating database \"$db_name\"."
	createdb -O "$owner" "$db_name"
fi